// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Xyz
{
    [XyzResourceType("xyz:index:Todo")]
    public partial class Todo : Pulumi.CustomResource
    {
        [Output("completed")]
        public Output<bool> Completed { get; private set; } = null!;

        [Output("order")]
        public Output<int> Order { get; private set; } = null!;

        [Output("title")]
        public Output<string> Title { get; private set; } = null!;

        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Todo resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Todo(string name, TodoArgs args, CustomResourceOptions? options = null)
            : base("xyz:index:Todo", name, args ?? new TodoArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Todo(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("xyz:index:Todo", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Todo resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Todo Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Todo(name, id, options);
        }
    }

    public sealed class TodoArgs : Pulumi.ResourceArgs
    {
        [Input("completed")]
        public Input<bool>? Completed { get; set; }

        [Input("order")]
        public Input<int>? Order { get; set; }

        [Input("title", required: true)]
        public Input<string> Title { get; set; } = null!;

        [Input("url")]
        public Input<string>? Url { get; set; }

        public TodoArgs()
        {
        }
    }
}
